pipeline {
    agent any
    tools { 
      maven 'Maven3'
    }

    stages {
	stage('Clean the Workspace') {
            steps {
                echo 'Clean the Workspace'
                sh "mvn clean"
            }
        }
    stages {
	stage('Building the Image') {
            steps {
                echo 'Clean the Workspace'
                sh "mvn install"
            }
        }
	stage('Deploy to PROD') {
            steps {
                input 'Do you want to continue deployment to PROD?'
		echo 'Deploy to PROD'		
            }
        }	
    }
}
